abort "Please use Ruby 1.9!" if RUBY_VERSION !~ /^1\.9/

require "bundler/setup"


namespace :docs do
  def doc_args
    "#{Dir.glob("js/awe/*").join(' ')} -t docs.emberjs.com"
  end

  desc "Preview Ember Docs (does not auto update)"
  task :preview do
    require "ember_docs/cli"
    EmberDocs::CLI.start("preview #{doc_args}".split(' '))
  end

  desc "Build Ember Docs"
  task :build do
    require "ember_docs/cli"
    EmberDocs::CLI.start("generate #{doc_args} -o docs".split(' '))
  end

  desc "Remove Ember Docs"
  task :clean do
    rm_r "docs"
  end
end
