defaults: &defaults
  jabber_server_base: "jabber.wack-a-doo.com"
  
development:
  <<: *defaults
  
test:
  <<: *defaults

staging:
  <<: *defaults
  jabber_server_base: "jabber.wack-a-doo.com"


production:
  <<: *defaults
  jabber_server_base: "jabber_runde2.wack-a-doo.com"

