defaults: &defaults
  jabber_server_base: "jabber.wack-a-doo.com"
  portal_server_base: "localhost"
  shop_callback_hostname: "test2" # linked per nginx to patrick's ip
  
  use_dynamic_construction_slots: true

  like_system_enabled: true
  shop_enabled: true
  jabber_id: "none"
  jabber_pwd: "none"
  
  
  
development:
  <<: *defaults
  
  jabber_id: "service"
  jabber_pwd: "P5Dda5eZmvCLFTw2"
  
  
test:
  <<: *defaults

staging:
  <<: *defaults
  jabber_server_base: "jabber.wack-a-doo.com"
  portal_server_base: "test1.wack-a-doo.de"
  shop_callback_hostname: "test1"
  
  use_dynamic_construction_slots: true
  
  shop_enabled: true


production:
  <<: *defaults
  jabber_server_base: "jabber2.wack-a-doo.com"
  portal_server_base: "wack-a-doo.de"
  shop_callback_hostname: "gs02"
  like_system_enabled: true  

