defaults: &defaults
  bosh_server_base:      "jabber3.wack-a-doo.com"
  jabber_server_base:    "jabber3.wack-a-doo.com"
  portal_server_base:    "localhost"
  shop_callback_hostname: "test2" # linked per nginx to patrick's ip
  
  use_dynamic_construction_slots: true

  like_system_enabled: true
  shop_enabled: true
  jabber_id: "none"
  jabber_pwd: "none"
  
  identity_provider_base_url: 'https://wack-a-doo.de/identity_provider'
  
  
development:
  <<: *defaults
  
  jabber_id: "service"
  jabber_pwd: "P5Dda5eZmvCLFTw2"
  
  
test:
  <<: *defaults

staging:
  <<: *defaults
  bosh_server_base:    "jabber3.wack-a-doo.com"
  jabber_server_base:  "jabber3.wack-a-doo.com"
  portal_server_base:  "test1.wack-a-doo.de"
  shop_callback_hostname: "test1"
  
  use_dynamic_construction_slots: true
  
  shop_enabled: true


production:
  <<: *defaults
  bosh_server_base:    "jabber5.wack-a-doo.com"
  jabber_server_base:  "jabber5.wack-a-doo.com"
  portal_server_base: "wack-a-doo.de"
  shop_callback_hostname: "gs04"
  like_system_enabled: true  

