defaults: &defaults
  jabber_server_base: "jabber.wack-a-doo.com"
  portal_server_base: "localhost"
  
development:
  <<: *defaults
  
test:
  <<: *defaults

staging:
  <<: *defaults
  jabber_server_base: "jabber.wack-a-doo.com"
  portal_server_base: "test1.wack-a-doo.de"


production:
  <<: *defaults
  jabber_server_base: "jabber2.wack-a-doo.com"
  portal_server_base: "wack-a-doo.de"

