---
pid: /var/run/client.pid
timeout: 30
wait: 30
log: log/thin/client.log
max_conns: 1024
require: []

environment: staging
max_persistent_conns: 512
servers: 3
daemonize: true
chdir: /var/www/html_client/current
socket: /var/run/client.sock